### ISSUE TITLE
Sidebar Images

### ISSUE THREAD

**Issue by ghost** [ayn/wp-jquery-lazy-load#1]
It seems you are reading the code of the page to do the lazy load instead of what is actually in the view port. In wordpress the sidebar is included after the content. So any images is my sidebars do not show up until you have scrolled to the very bottom of the page.

We need some sort of sidebar fix, or use the real viewport opposed to code.

**Comment by ayn** [comment]
Feel free to submit a pull request.

/ayn
http://andrewng.me

On Jun 15, 2011, at 8:11 AM, jwilkinson
reply@reply.github.com
wrote:
