### ISSUE TITLE
Not working with WP 3.2

### ISSUE THREAD

**Issue by ralev** [ayn/wp-jquery-lazy-load#2]
just to report that the plugin is not working with the latest WP version :)

Best,
M.

PS: Hm... after delete & reinstall - it seems to have start working again... 
weird.

**Comment by ayn** [comment]
My blog is on 3.2 and it works there. You have a URL I can look it?

/ayn

## 

Andrew Ng
http://andrewng.me

On Jul 10, 2011, at 6:12, ralev
reply@reply.github.com
wrote:

**Comment by ralev** [comment]
the site is http://ralev.com/ ,  but now it's working so I can't say what was the problem exactly. 

I just updated the WP and then played a little bit with the function that's calling the thumbs on the frontpage. Then I've noticed that it's not lazy loading the pictures... and then I deactivated and deleted the plugin.
After finishing playing with the function I've downloaded and installed again Lazy Load... and it's now working :)

It's a great plugin. Thank you for making it!

**Comment by ayn** [comment]
Glad to hear it's working, I update my wp installation pretty often via
subversion, I excluded a bunch of selectors at my blog, like the sidebar
stuff, but it works great otherwise.

/ayn

## 

Andrew Ng (@ayn http://twitter.com/ayn)
andrewng.me
