### ISSUE TITLE
Undefined class_attr variable

### ISSUE THREAD

**Issue by stellarboy** [ayn/wp-jquery-lazy-load#5]
I enable WP_DEBUG on a client's website (http://seointhemaking.com) and there's an error that says:

"Undefined variable: class_attr in /home/*****_/public_html/**_**_-**_**/wp-content/plugins/jquery-image-lazy-loading/jq_img_lazy_load.php on line 57"

(server name & site subfolder name retracted for security purposes).

Is it probably for a incompatibility, or an issue with invoking $class_attr when linking an image?

Thanks.

**Comment by ayn** [comment]
@stellarboy the plugin seems to be working at the URL above, is this still an issue?
